// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjogicbqdphksxeogjdz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qb2dpY2JxZHBoa3N4ZW9namR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNjQ2NDgsImV4cCI6MjA3Mjk0MDY0OH0.VZBc6jKL54LSUAxQLaGrHG1vONMxDp922NRJq4EddUA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});